### PR TITLE
Allow newer versions of dependant packages

### PR DESCRIPTION
**Pull request by pintaf**

### CODE REVIEW

**Comment by Tofandel** [comment]
The update is much needed

Supersedes #10

**Comment by rmarmitt** [comment]
Any updates about this PR?

**Comment by Tofandel** [comment]
@pintaf Can you bump `eslint-config-standard` to 17? It's just been released and it's what was missing for eslint 8 support

**Comment by pintaf** [comment]
@Tofandel Done.

**Pull request closed without merging**
